-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.assessment_results (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  first_name text,
  last_name text,
  date_taken text,
  total_correct integer,
  total_questions integer,
  percentage integer,
  grade text,
  sec_a_score text,
  sec_a_pct integer,
  sec_b_score text,
  sec_b_pct integer,
  sec_c_score text,
  sec_c_pct integer,
  sec_d_score text,
  sec_d_pct integer,
  sec_e_score text,
  sec_e_pct integer,
  sec_f_score text,
  sec_f_pct integer,
  sec_g_score text,
  sec_g_pct integer,
  sec_h_score text,
  sec_h_pct integer,
  question_detail text,
  section_summary text,
  study_plan text,
  time_taken_seconds integer,
  time_taken_formatted text,
  CONSTRAINT assessment_results_pkey PRIMARY KEY (id)
);
CREATE TABLE public.python_assessment_results (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  first_name text,
  last_name text,
  date_taken text,
  total_correct integer,
  total_questions integer,
  percentage integer,
  grade text,
  time_taken_seconds integer,
  time_taken_formatted text,
  sec_a_score text,
  sec_a_pct integer,
  sec_b_score text,
  sec_b_pct integer,
  sec_c_score text,
  sec_c_pct integer,
  sec_d_score text,
  sec_d_pct integer,
  sec_e_score text,
  sec_e_pct integer,
  sec_f_score text,
  sec_f_pct integer,
  sec_g_score text,
  sec_g_pct integer,
  question_detail text,
  section_summary text,
  study_plan text,
  sec_h_score text,
  sec_h_pct integer,
  fitb_detail text,
  full_breakdown text,
  CONSTRAINT python_assessment_results_pkey PRIMARY KEY (id)
);
CREATE TABLE public.python_exercise_results (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text,
  submitted_at timestamp with time zone,
  total_score integer,
  s1_score integer,
  s2_score integer,
  s3_score integer,
  s4_score integer,
  s5_score integer,
  answers jsonb,
  attempts jsonb,
  w19_code text,
  w20_code text,
  w21_code text,
  w22_code text,
  w23_code text,
  w24_code text,
  w25_code text,
  CONSTRAINT python_exercise_results_pkey PRIMARY KEY (id)
);
CREATE TABLE public.caio_test_results (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text,
  submitted_at timestamp with time zone,
  mcq_score integer,
  blank_score integer,
  auto_score integer,
  mcq_details jsonb,
  q16_b1 text,
  q16_b2 text,
  q16_b3 text,
  q16_b4 text,
  q16_b5 text,
  q16_b6 text,
  q19_b1 text,
  q19_b2 text,
  q19_b3 text,
  q19_b4 text,
  q19_b5 text,
  q19_b6 text,
  q19_b7 text,
  q20_b1 text,
  q20_b2 text,
  q17_text text,
  q18_text text,
  q21_text text,
  CONSTRAINT caio_test_results_pkey PRIMARY KEY (id)
);
CREATE TABLE public.homework_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_name text NOT NULL,
  class_number integer,
  homework_title text,
  score integer,
  total integer,
  pct integer,
  question_detail jsonb,
  started_at timestamp with time zone,
  submitted_at timestamp with time zone DEFAULT now(),
  access_code text,
  cohort text,
  CONSTRAINT homework_submissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.access_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  class_number integer NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  max_uses integer DEFAULT 999,
  uses_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  cohort text NOT NULL DEFAULT 'aijr'::text,
  CONSTRAINT access_codes_pkey PRIMARY KEY (id),
  CONSTRAINT access_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.class_config (
  class_number integer NOT NULL,
  title text NOT NULL,
  subtitle text NOT NULL,
  description text,
  homework_title text,
  module_badge text,
  difficulty_badge text,
  exam_links text,
  msg_perfect text,
  msg_good text,
  msg_ok text,
  msg_retry text,
  CONSTRAINT class_config_pkey PRIMARY KEY (class_number)
);
CREATE TABLE public.questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_number integer NOT NULL,
  question_number integer NOT NULL,
  section_number integer NOT NULL,
  section_title text NOT NULL,
  section_exam_note text,
  question_text text NOT NULL,
  code_snippet text,
  option_a text NOT NULL,
  option_b text NOT NULL,
  option_c text NOT NULL,
  option_d text NOT NULL,
  correct_answer integer NOT NULL CHECK (correct_answer >= 1 AND correct_answer <= 4),
  explanation text NOT NULL,
  hint_1 text,
  hint_2 text,
  is_exam_linked boolean DEFAULT false,
  exam_q_reference text,
  CONSTRAINT questions_pkey PRIMARY KEY (id),
  CONSTRAINT questions_class_number_fkey FOREIGN KEY (class_number) REFERENCES public.class_config(class_number)
);
CREATE TABLE public.project_progress_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  student_name text NOT NULL,
  project_title text NOT NULL,
  session_date date,
  phase text,
  accomplishments text,
  confidence_rating smallint CHECK (confidence_rating >= 1 AND confidence_rating <= 5),
  ai_tools ARRAY DEFAULT '{}'::text[],
  tools_working text CHECK (tools_working = ANY (ARRAY['Yes'::text, 'No'::text, 'Partially'::text])),
  tools_issue text,
  seed_changed text CHECK (seed_changed = ANY (ARRAY['Yes'::text, 'No'::text])),
  seed_change_reason text,
  bias_identified text,
  responsible_use text,
  task_1 text,
  task_2 text,
  task_3 text,
  instructor_question text,
  slide_link text,
  CONSTRAINT project_progress_notes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.final_project_definitions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  student_name text NOT NULL,
  project_title text NOT NULL,
  submission_date date,
  project_type text,
  one_sentence text,
  ai_tools ARRAY DEFAULT '{}'::text[],
  audience text,
  problem_solved text,
  how_used text,
  core_feature text,
  feature_1 text,
  feature_2 text,
  feature_3 text,
  success_looks_like text,
  limitations text,
  responsible_checks ARRAY DEFAULT '{}'::text[],
  responsible_choice text,
  elevator_pitch text,
  most_excited text,
  CONSTRAINT final_project_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.caio_final_exam_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_name text NOT NULL,
  class_number integer DEFAULT 16,
  access_code text,
  submitted_at timestamp with time zone DEFAULT now(),
  mcq_score integer,
  blank_score integer,
  auto_score integer,
  mcq_details jsonb,
  q16_b1 text,
  q16_b2 text,
  q16_b3 text,
  q16_b4 text,
  q16_b5 text,
  q16_b6 text,
  q19_b1 text,
  q19_b2 text,
  q19_b3 text,
  q19_b4 text,
  q19_b5 text,
  q19_b6 text,
  q20_b1 text,
  q20_b2 text,
  q20_b3 text,
  q20_b4 text,
  q20_b5 text,
  q17_text text,
  q18_text text,
  q21_text text,
  CONSTRAINT caio_final_exam_results_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cohorts (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_by uuid,
  CONSTRAINT cohorts_pkey PRIMARY KEY (id),
  CONSTRAINT cohorts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.introai_week01_registrations (
  id bigint NOT NULL DEFAULT nextval('introai_week01_registrations_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text NOT NULL,
  registered_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week01_registrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week01_scores (
  id bigint NOT NULL DEFAULT nextval('introai_week01_scores_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text NOT NULL,
  score integer NOT NULL CHECK (score >= 0),
  total integer NOT NULL CHECK (total > 0),
  rank text,
  completed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week01_scores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week01_scavenger_hunt (
  id bigint NOT NULL DEFAULT nextval('introai_week01_scavenger_hunt_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text NOT NULL,
  tool_name text NOT NULL,
  tool_category text,
  tool_description text,
  ai_instance_1 text,
  ai_instance_2 text,
  ai_instance_3 text,
  ai_instance_4 text,
  ai_instance_5 text,
  instance_count smallint NOT NULL DEFAULT 3 CHECK (instance_count >= 1 AND instance_count <= 5),
  surprised text,
  reflection text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week01_scavenger_hunt_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week01_chatbots (
  id bigint NOT NULL DEFAULT nextval('introai_week01_chatbots_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text NOT NULL,
  chatbot_used text NOT NULL,
  t1_chatbot_definition text,
  t1_comparison text,
  t1_notes text,
  t2_question text,
  t2_chatbot_answer text,
  t2_accuracy text,
  t3_original_text text,
  t3_chatbot_summary text,
  t3_summary_quality text,
  t4_creative_prompt text,
  t4_creative_response text,
  overall_impression smallint CHECK (overall_impression >= 1 AND overall_impression <= 5),
  reflection text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week01_chatbots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week01_self_assessment (
  id bigint NOT NULL DEFAULT nextval('introai_week01_self_assessment_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text NOT NULL,
  q1_explain_ai smallint NOT NULL CHECK (q1_explain_ai >= 1 AND q1_explain_ai <= 5),
  q2_rule_vs_ai smallint NOT NULL CHECK (q2_rule_vs_ai >= 1 AND q2_rule_vs_ai <= 5),
  q3_real_world_apps smallint NOT NULL CHECK (q3_real_world_apps >= 1 AND q3_real_world_apps <= 5),
  q4_ml_understanding smallint NOT NULL CHECK (q4_ml_understanding >= 1 AND q4_ml_understanding <= 5),
  q5_training_data smallint NOT NULL CHECK (q5_training_data >= 1 AND q5_training_data <= 5),
  q6_ai_bias smallint NOT NULL CHECK (q6_ai_bias >= 1 AND q6_ai_bias <= 5),
  q7_ethical_concerns smallint NOT NULL CHECK (q7_ethical_concerns >= 1 AND q7_ethical_concerns <= 5),
  q8_responsible_use smallint NOT NULL CHECK (q8_responsible_use >= 1 AND q8_responsible_use <= 5),
  q9_fact_check_ai smallint NOT NULL CHECK (q9_fact_check_ai >= 1 AND q9_fact_check_ai <= 5),
  q10_chatbot_comfort smallint NOT NULL CHECK (q10_chatbot_comfort >= 1 AND q10_chatbot_comfort <= 5),
  q11_prompt_writing smallint NOT NULL CHECK (q11_prompt_writing >= 1 AND q11_prompt_writing <= 5),
  q12_ai_creation_tools smallint NOT NULL CHECK (q12_ai_creation_tools >= 1 AND q12_ai_creation_tools <= 5),
  q13_industry_impact smallint NOT NULL CHECK (q13_industry_impact >= 1 AND q13_industry_impact <= 5),
  q14_ai_opinion smallint NOT NULL CHECK (q14_ai_opinion >= 1 AND q14_ai_opinion <= 5),
  q15_excitement smallint NOT NULL CHECK (q15_excitement >= 1 AND q15_excitement <= 5),
  avg_section_a numeric,
  avg_section_b numeric,
  avg_section_c numeric,
  avg_section_d numeric,
  avg_section_e numeric,
  overall_avg numeric,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week01_self_assessment_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week02_persona_detective (
  id bigint NOT NULL DEFAULT nextval('introai_week02_persona_detective_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text,
  secret_persona text NOT NULL,
  teacher_question text NOT NULL,
  prompt_used text NOT NULL,
  chatbot_used text NOT NULL,
  ai_response text NOT NULL,
  was_guessed boolean NOT NULL,
  guess_time_seconds smallint,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week02_persona_detective_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week02_creative_prompting (
  id bigint NOT NULL DEFAULT nextval('introai_week02_creative_prompting_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text,
  chatbot_used text NOT NULL,
  initial_prompt text NOT NULL,
  initial_response text NOT NULL,
  followed_task boolean NOT NULL,
  followed_tone boolean NOT NULL,
  followed_persona boolean NOT NULL,
  followed_format boolean NOT NULL,
  actual_line_count smallint,
  refined_prompt text,
  refined_response text,
  learning_takeaway text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week02_creative_prompting_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week02_co_writer_story (
  id bigint NOT NULL DEFAULT nextval('introai_week02_co_writer_story_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text,
  class_number text NOT NULL,
  prompt_used text,
  story_text text NOT NULL,
  sequence_order integer NOT NULL,
  is_visible boolean NOT NULL DEFAULT true,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week02_co_writer_story_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week03_ai_pictionary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text NOT NULL,
  secret_cliche text NOT NULL,
  art_style text,
  lighting text,
  setting text,
  mood text,
  prompt_used text NOT NULL,
  ai_tool_used text,
  result_notes text,
  generated_image_url text,
  was_guessed boolean,
  reflection text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week03_ai_pictionary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week03_prompt_comparison (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text NOT NULL,
  style_tool text,
  style_fave_prompt text,
  style_observations text,
  style_image_url text,
  detail_tool text,
  detail_fave_prompt text,
  detail_observations text,
  detail_image_url text,
  freestyle_tool text,
  freestyle_prompt text,
  freestyle_result text,
  freestyle_image_url text,
  share_highlight text,
  big_takeaway text,
  enjoyment_rating smallint CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week03_prompt_comparison_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week04_music_generation (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text NOT NULL,
  study_tool text NOT NULL,
  study_link text NOT NULL,
  study_observations text NOT NULL,
  edm_tool text NOT NULL,
  edm_link text NOT NULL,
  edm_observations text NOT NULL,
  pop_tool text NOT NULL,
  pop_link text NOT NULL,
  pop_observations text NOT NULL,
  big_takeaway text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week04_music_generation_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week04_instrument_swap (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text NOT NULL,
  scenario_chosen text NOT NULL,
  ai_tool_used text NOT NULL,
  prompt_used text NOT NULL,
  music_link text NOT NULL,
  observations text NOT NULL,
  big_takeaway text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week04_instrument_swap_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week05_train_your_model (
  id bigint NOT NULL DEFAULT nextval('introai_week05_train_your_model_id_seq'::regclass),
  student_name text NOT NULL,
  student_email text,
  project_type text NOT NULL,
  project_title text NOT NULL,
  classes_trained text NOT NULL,
  examples_per_class text NOT NULL,
  model_url text NOT NULL,
  accuracy_rating text NOT NULL,
  challenges_reflections text NOT NULL,
  improvement_ideas text NOT NULL,
  enjoyment_rating smallint NOT NULL,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week05_train_your_model_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week06_be_the_algorithm (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  profiles_used text NOT NULL,
  profile_a_recommendation text,
  profile_b_recommendation text,
  profile_c_recommendation text,
  profile_d_recommendation text,
  profile_e_recommendation text,
  profile_a_key_param text,
  profile_b_key_param text,
  profile_c_key_param text,
  profile_d_key_param text,
  profile_e_key_param text,
  hardest_profile text NOT NULL,
  algorithm_strategy text NOT NULL,
  class_consensus text NOT NULL,
  real_world_connection text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week06_be_the_algorithm_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week06_analyze_your_feed (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  platforms_used text NOT NULL,
  fav_recommendation text NOT NULL,
  personalization_rating text NOT NULL,
  how_it_knows text NOT NULL,
  got_weird_rec text NOT NULL,
  weird_example text NOT NULL,
  filter_bubble_status text NOT NULL,
  bubble_reflection text NOT NULL,
  break_bubble_idea text,
  ai_ethics_thought text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week06_analyze_your_feed_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week06_design_a_recommender (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  input_questions text NOT NULL,
  num_decision_steps text NOT NULL,
  flowchart_json text NOT NULL,
  flowchart_summary text,
  output_games text NOT NULL,
  hardest_part text NOT NULL,
  rule_limitations text NOT NULL,
  real_vs_simple text,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week06_design_a_recommender_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week07_spot_the_bias (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  scenario_a_left_out text NOT NULL,
  scenario_a_harm text NOT NULL,
  scenario_a_fix text NOT NULL,
  scenario_b_left_out text NOT NULL,
  scenario_b_harm text NOT NULL,
  scenario_b_fix text NOT NULL,
  scenario_c_left_out text NOT NULL,
  scenario_c_harm text NOT NULL,
  scenario_c_fix text NOT NULL,
  final_reflection text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week07_spot_the_bias_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week07_data_audit (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  app_1_name text NOT NULL,
  app_1_data_collected text NOT NULL,
  app_1_how_used text NOT NULL,
  app_1_worth_tradeoff text NOT NULL,
  app_2_name text NOT NULL,
  app_2_data_collected text NOT NULL,
  app_2_how_used text NOT NULL,
  app_2_worth_tradeoff text NOT NULL,
  app_3_name text NOT NULL,
  app_3_data_collected text NOT NULL,
  app_3_how_used text NOT NULL,
  app_3_worth_tradeoff text NOT NULL,
  app_4_name text,
  app_4_data_collected text,
  app_4_how_used text,
  app_4_worth_tradeoff text,
  surprising_app_reflection text NOT NULL,
  opinion_changed_reflection text NOT NULL,
  behavior_change_reflection text NOT NULL,
  privacy_challenge text,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week07_data_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week07_data_detective (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  dataset_chosen text NOT NULL,
  data_types_identified text NOT NULL,
  data_types_explanation text NOT NULL,
  pattern_1_description text NOT NULL,
  pattern_2_description text NOT NULL,
  ai_prediction_usecase text NOT NULL,
  ai_pitfalls_reflections text NOT NULL,
  chart_visualization_idea text,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week07_data_detective_pkey PRIMARY KEY (id)
);
CREATE TABLE public.test_access_codes (
  id bigint NOT NULL DEFAULT nextval('test_access_codes_id_seq'::regclass),
  code text NOT NULL UNIQUE,
  test_id text NOT NULL,
  cohort text,
  max_uses integer NOT NULL DEFAULT 1,
  uses_count integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT test_access_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.test_submissions (
  id bigint NOT NULL DEFAULT nextval('test_submissions_id_seq'::regclass),
  student_name text NOT NULL,
  test_id text NOT NULL,
  access_code text,
  mcq_score integer,
  blank_score integer,
  auto_score integer,
  total_possible integer,
  pct numeric,
  question_detail jsonb,
  started_at timestamp with time zone,
  submitted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT test_submissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week08_bias_card_twist (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  group_members text,
  local_problem text NOT NULL,
  initial_ai_solution text NOT NULL,
  twist_card text NOT NULL,
  what_breaks text NOT NULL,
  who_left_out text NOT NULL,
  debrief_reflection text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week08_bias_card_twist_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week08_bias_detective_stations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  group_members text,
  st1_bias_source text NOT NULL,
  st1_who_gets_hurt text NOT NULL,
  st2_bias_source text NOT NULL,
  st2_who_gets_hurt text NOT NULL,
  st3_bias_source text NOT NULL,
  st3_who_gets_hurt text NOT NULL,
  st4_bias_source text NOT NULL,
  st4_who_gets_hurt text NOT NULL,
  favorite_station_share text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week08_bias_detective_stations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week08_fix_the_dataset (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  partner_name text,
  initial_dataset_summary text NOT NULL,
  final_dataset_summary text NOT NULL,
  modified_dataset_json text,
  changes_explanation text NOT NULL,
  debrief_reflection text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week08_fix_the_dataset_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week08_mini_ethics_trial (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  role_selected text NOT NULL,
  case_argument text NOT NULL,
  followup_qa text NOT NULL,
  verdict_ruling text NOT NULL,
  debrief_reflection text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week08_mini_ethics_trial_pkey PRIMARY KEY (id)
);
CREATE TABLE public.introai_week08_promise_vs_problem (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_name text NOT NULL,
  student_email text UNIQUE,
  partner_name text,
  alphafold_promise text NOT NULL,
  alphafold_problem text NOT NULL,
  woebot_promise text NOT NULL,
  woebot_problem text NOT NULL,
  bemyeyes_promise text NOT NULL,
  bemyeyes_problem text NOT NULL,
  ocean_cleanup_promise text NOT NULL,
  ocean_cleanup_problem text NOT NULL,
  debrief_reflection text NOT NULL,
  enjoyment_rating smallint NOT NULL CHECK (enjoyment_rating >= 1 AND enjoyment_rating <= 5),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT introai_week08_promise_vs_problem_pkey PRIMARY KEY (id)
);